# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56a1bdb47d22092a140a01ecb82dc2f1b25740efcc5853445542e5586937051d0b082d691204ae985058360db23bfce3337d47b3be1cf6c207edefbd23d00ea8

test:
  secret_key_base: 9a77675ec0d55d2aa66eef26ecf6693518fc1e3b04e842d20d7bda50c73f290f43459e46b3dd9ef62c1b18fce3ea7c7b107bca59e8d501c9a61f5d3c018cc176

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
